### ISSUE TITLE
Segmentation fault on startup with Spring Boot applications using Eclipse Temurin 17/21 and google-maps-routing library

### ISSUE THREAD

**Issue by bogdanstan1805** [adoptium/adoptium-support#1210]
### Please provide a brief summary of the bug

Spring Boot applications built on Docker images using Eclipse Temurin 17 or 21 as the base JRE are encountering segmentation faults during startup when including the google-maps-routing library in the project. This issue consistently occurs across different Spring Boot applications and varying Docker environments when using the specified Temurin versions and the mentioned library.

Environment:

Spring Boot version: 3.2.7
google-maps-routing version: 1.39.0, 1.40.0 (and other versions)

Link to public repo:
https://bitbucket.org/medicaar/issue-segv-google-routing-jre21/src/master/
There are some 2 Dockerfiles with the eclipse temurin 17 and 21 base image and one with amazon corretto that is working. 

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

- Create a Dockerfile using Eclipse Temurin 17 or 21 as the base image (e.g., eclipse-temurin:17.0.6_10-jre-alpine).
- Add a Spring Boot application JAR to the Docker image.
- Ensure the Spring Boot application includes the following dependency in the build.gradle file:
         implementation 'com.google.maps:google-maps-routing:1.39.0' 
- Define the entry point to execute the Spring Boot application (e.g., ENTRYPOINT ["java", "-jar", "app.jar"]).
- Build the Docker image.
- Run the Docker container.

### Expected Results

The Spring Boot application should start up successfully without any segmentation faults.

### Actual Results

The container terminates shortly after startup with a segmentation fault error.

### What Java Version are you using?

17.0.6

### What is your operating system and platform?

MacOS ARM64

### Did you test with other Java versions?

```Shell
Tested with: 
eclipse-temurin:17.0.6_10-jre-alpine - seg fault
eclipse-temurin:21.0.5_11-jre-alpine - seg fault
amazoncorretto:17.0.13-al2023-headful - works
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000204b6, pid=1, tid=9
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00000000000204b6
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /app/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by karianna** [comment]
This was fixed in temurin 17.0.13 , please upgrade

**Comment by bogdanstan1805** [comment]
Still occurring on latest 21 image
eclipse-temurin:21.0.6_7-jre-alpine-3.21
Also upgraded routes api to 1.45.0 to check with the latest version.

**Comment by karianna** [comment]
OK, this is a crash in the native nerry lib, you should report that to the netty lib maintainers.
