### ISSUE TITLE
Add openjdk11 to homebrew.

### ISSUE THREAD

**Issue by Jee-Bee** [adoptium/adoptium-support#382]
## Question

Is it an idea to add the OpenJDK11 lts to homebrew?
Currently only OpenJDK8 (adoptopenjdk8) and the latest version(adoptopenjdk) exist.
 I expect that OpenJDK11 becomes more important packages as Eclipse-Papyrus(https://www.eclipse.org/papyrus/) switch to OpenJDK11.

## Context

Java version:

11

Your operating system and platform:

OSX 10.xx - OSX 11.X

**Comment by karianna** [comment]
https://formulae.brew.sh/cask/temurin

**Comment by karianna** [comment]
@gdams - I just noticed - our installation page at Adoptium doesn't mention Homebrew - is it elsewhere or something that needs fixing?

**Comment by Jee-Bee** [comment]
> https://formulae.brew.sh/cask/temurin

I have installed this version. but when opening Eclipse Payrus 5.0 / 5.2 i got a error message
`The JVM shared library "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/../lib/server/libjvm.dylib"
does not contain the JNI_CreateJavaVM symbol.`
Is this related to java or to Papyrus Eclipse? At least when i start looking to the error message i read in some methods that i have to change some files of java itself. I don't want that because it means that i have to this after every java update.
Is that an issue i can post here on Github(new ticket) or do i have to go to the eclipse papyrus forum and ask there?

**Comment by karianna** [comment]
> > https://formulae.brew.sh/cask/temurin
> 
> I have installed this version. but when opening Eclipse Payrus 5.0 / 5.2 i got a error message `The JVM shared library "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/../lib/server/libjvm.dylib" does not contain the JNI_CreateJavaVM symbol.` Is this related to java or to Papyrus Eclipse? At least when i start looking to the error message i read in some methods that i have to change some files of java itself. I don't want that because it means that i have to this after every java update. Is that an issue i can post here on Github(new ticket) or do i have to go to the eclipse papyrus forum and ask there?

This is an issue with Deep Signing on the Mac Binaries from the last release.  This has been resolved and we're spinning a new release this week.  See adoptium.net

**Comment by gdams** [comment]
This is now complete

**Comment by GauthierPLM** [comment]
Hello,
The website still does not mention Brew (only winget is mentioned in package managers).
Is there any plan to update the documentation/place we could contribute to add it?
Best regards,
